project:
  type: website
  output-dir: docs
  
website:
  title: "Jean Luis Soto's Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jeanlsoto54
      - icon: linkedin
        href: https://www.linkedin.com/in/jeanluissoto/
format:
  html:
    theme: cosmo
    css: styles.css



